# Change these first
owner: BusDriver5YT # Your GitHub organization or username, where this repository lives
repo: upptime.moonlightsimulations.org # The name of this repository
skipDeleteIssues: true
user-agent: upptime-bot

sites:
  - name: Moonlight Simulations
    url: https://bounce.moonlightsimulations.org
  - name: MSRP Server & Admin Panel
    url: https://bounce.moonlightsimulations.org
    icon: https://static.wixstatic.com/media/af0f76_fda78d8d370440ce8320fd7f31936dc4~mv2.png
  - name: Moonlight Simulations Cad
    url: https://bounce.moonlightsimulations.org
    icon: https://static.wixstatic.com/media/af0f76_fda78d8d370440ce8320fd7f31936dc4~mv2.png

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: upptime.moonlightsimulations.org
  theme: dark
  logoUrl: https://static.wixstatic.com/media/8f3f10_af4b5258a29342a583a6d8b5b582ba08~mv2.png
  favicon: https://static.wixstatic.com/media/8f3f10_af4b5258a29342a583a6d8b5b582ba08~mv2.png
  # baseUrl: /your-repo-name
  name: Moonlight Simulations
  introTitle: "Our status page is going away today on 2026"
  introMessage: We are moving over to [SCN's Status Page](https://status.starlightcommunity.network) as its not worth updating 2 status pages now that Moonlight RP is shuting down we appreate your support and we hope to see you there.
  metaTags:
    - name: "theme-color"
      content: "#fe5926" 
    - name: "og:site_name"
      content: "Moonlight Simulations Powered By Upptime"
    - name: "og:type"
      content: "website" 
    - name: "og:title"
      content: "Moonlight Simulations | Status (Going Away)"
    - name: "og:description"
      content: "Stay informed with real-time updates on our service status. Check for outages, scheduled maintenance, and performance metrics to ensure seamless connectivity."
    - name: "og:image"
      content: "https://static.wixstatic.com/media/8f3f10_af4b5258a29342a583a6d8b5b582ba08~mv2.png"
    - name: "http-equiv="Refresh"
      content: "content="15; url='https://satus.starlightcommunity.network'"
  navbar:
    - title: Status
      href: /
    - title: Main Site
      href: https://www.moonlightsimulations.org
    - title: SCN Status page
      href: https://status.starlightgaming.network
i18n:
  footer: move yoUR F###ING SCOOTER! *crashes*

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
